package org.silnith.grammar.sql;

import org.silnith.grammar.TerminalSymbol;

public enum Terminals implements TerminalSymbol {
    simple_Latin_upper_case_letter,
    simple_Latin_lower_case_letter,
    digit,
    space,
    double_quote,
    percent,
    ampersand,
    quote,
    left_paren,
    right_paren,
    asterisk,
    plus_sign,
    comma,
    minus_sign,
    period,
    solidus,
    colon,
    semicolon,
    less_than_operator,
    greater_than_operator,
    equals_operator,
    question_mark,
    underscore,
    vertical_bar,
    unsigned_numeric_literal,
    exact_numeric_literal,
    unsigned_integer,
    approximate_numeric_literal,
    mantissa,
    exponent,
    signed_integer,
    sign,
    national_character_string_literal,
    character_representation,
    nonquote_character,
    quote_symbol,
    separator,
    comment,
    comment_introducer,
    comment_character,
    newline,
    bit_string_literal,
    bit,
    hex_string_literal,
    hexit,
    delimiter_token,
    character_string_literal,
    introducer,
    character_set_specification,
    standard_character_repertoire_name,
    character_set_name,
    schema_name,
    catalog_name,
    identifier,
    actual_identifier,
    delimited_identifier,
    delimited_identifier_body,
    delimited_identifier_part,
    nondoublequote_character,
    doublequote_symbol,
    unqualified_schema_name,
    SQL_language_identifier,
    SQL_language_identifier_start,
    SQL_language_identifier_part,
    implementation_defined_character_repertoire_name,
    user_defined_character_repertoire_name,
    standard_universal_character_form_of_use_name,
    implementation_defined_universal_character_form_of_use_name,
    date_string,
    date_value,
    years_value,
    datetime_value,
    months_value,
    days_value,
    time_string,
    time_value,
    hours_value,
    minutes_value,
    seconds_value,
    seconds_integer_value,
    seconds_fraction,
    time_zone_interval,
    timestamp_string,
    interval_string,
    year_month_literal,
    day_time_literal,
    day_time_interval,
    time_interval,
    not_equals_operator,
    greater_than_or_equals_operator,
    less_than_or_equals_operator,
    concatenation_operator,
    double_period,
    /*
     * Everything below is a reserved word.
     */
    ABSOLUTE, ACTION, ADD, ALL, ALLOCATE, ALTER, AND, ANY, ARE,
    AS, ASC, ASSERTION, AT, AUTHORIZATION, AVG,
    BEGIN, BETWEEN, BIT, BIT_LENGTH, BOTH, BY,
    CASCADE, CASCADED, CASE, CAST, CATALOG, CHAR, CHARACTER, CHARACTER_LENGTH,
    CHAR_LENGTH, CHECK, CLOSE, COALESCE, COLLATE, COLLATION, COLUMN, COMMIT, COMMITTED,
    CONNECT, CONNECTION, CONSTRAINT, CONSTRAINTS, CONTINUE, CONVERT, CORRESPONDING, COUNT,
    CREATE, CROSS, CURRENT, CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, CURRENT_USER, CURSOR,
    DATE, DAY, DEALLOCATE, DEC, DECIMAL, DECLARE, DEFAULT,
    DEFERRABLE, DEFERRED, DELETE, DESC, DESCRIBE, DESCRIPTOR, DIAGNOSTICS,
    DISCONNECT, DISTINCT, DOMAIN, DOUBLE, DROP,
    ELSE, END, END_EXEC, ESCAPE, EXCEPT, EXCEPTION, EXEC, EXECUTE, EXISTS, EXTERNAL, EXTRACT,
    FALSE, FETCH, FIRST, FLOAT, FOR, FOREIGN, FOUND, FROM, FULL,
    GET, GLOBAL, GO, GOTO, GRANT, GROUP,
    HAVING, HOUR,
    IDENTITY, IMMEDIATE, IN, INDICATOR, INITIALLY, INNER, INPUT, INSENSITIVE,
    INSERT, INT, INTEGER, INTERSECT, INTERVAL, INTO, IS, ISOLATION,
    JOIN,
    KEY,
    LANGUAGE, LAST, LEADING, LEFT, LEVEL, LIKE, LOCAL, LOWER,
    MATCH, MAX, MIN, MINUTE, MODULE, MONTH,
    NAMES, NATIONAL, NATURAL, NCHAR, NEXT, NO, NOT, NULL, NULLIF, NUMERIC,
    OCTET_LENGTH, OF, ON, ONLY, OPEN, OPTION, OR, ORDER, OUTER, OUTPUT, OVERLAPS,
    PAD, PARTIAL, POSITION, PRECISION, PREPARE, PRESERVE, PRIMARY, PRIOR, PRIVILEGES, PROCEDURE, PUBLIC,
    READ, REAL, REFERENCES, RELATIVE, RESTRICT, REVOKE, RIGHT, ROLLBACK, REPEATABLE, ROWS,
    SCHEMA, SCROLL, SECOND, SECTION, SELECT, SERIALIZABLE, SESSION, SESSION_USER, SET,
    SIZE, SMALLINT, SOME, SPACE, SQL, SQLCODE, SQLERROR, SQLSTATE, SUBSTRING, SUM, SYSTEM_USER,
    TABLE, TEMPORARY, THEN, TIME, TIMESTAMP, TIMEZONE_HOUR, TIMEZONE_MINUTE,
    TO, TRAILING, TRANSACTION, TRANSLATE, TRANSLATION, TRIM, TRUE,
    UNCOMMITTED, UNION, UNIQUE, UNKNOWN, UPDATE, UPPER, USAGE, USER, USING,
    VALUE, VALUES, VARCHAR, VARYING, VIEW,
    WHEN, WHENEVER, WHERE, WITH, WORK, WRITE,
    YEAR,
    ZONE,
    end_of_file;
}